multi-platform builds (linux/amd64+linux/arm64) + test nginx serving state (no real end-to-end tests needed right now) (#56)
* add end-to-end testing to check nginx config

* improve build cache + add arm64

* add linter to composer test command

* update readme

* replace invalid chars in tag

* multi platform build

* test variables

* composer update

* curl

* platform

* build

* fix

* detect drivers for end-to-end test

* dont push cache image

* packages should be installed in final image, not in composer image

* push test image on failure

* try simple curl test

* faster healthcheck + run container in actions

* sanity check: this should fail...

* increase the first check a bit

* sanity check - without php-fpm it should fail to serve

* enable php-fpm again - it should succeed

* remove end-to-end test stuff

* changes

diff --git a/.github/workflows/job.docker-image.yml b/.github/workflows/job.docker-image.yml
--- a/.github/workflows/job.docker-image.yml
+++ b/.github/workflows/job.docker-image.yml
@@ -6,18 +6,23 @@ on:
       DOCKERHUB_USER:
         type: string
         default: rboonzaijer
-      DOCKER_PUSH_DEV:
+      DOCKER_PUSH:
         type: number
         default: 0
-      DOCKER_PUSH_RELEASE:
+      DOCKER_PUSH_LATEST:
         type: number
         default: 0
+      TARGET_IMAGE_TAG:
+        type: string
+        default: "dev-${{ github.ref_name }}"
       TARGET_IMAGE_PROD:
         type: string
         default: mysticeragames/makeitstatic-cms
       TARGET_IMAGE_TEST:
         type: string
         default: mysticeragames/makeitstatic-cms-test
+
+      # The build cache is used to cache Docker layers, used to speed up the build process
       TARGET_IMAGE_CACHE:
         type: string
         default: mysticeragames/makeitstatic-cms-buildcache
@@ -32,21 +37,25 @@ jobs:
     permissions:
       contents: read
 
-    env:
-      # - Remove special characters in tag name with sed
-      # - 2 images: prod/test (test has phpunit/chromedriver/etc) - push to a different repository (*-test) but using the same tag
-      IMAGE_DEV_PROD:     "${{ inputs.TARGET_IMAGE_PROD }}:dev-$( echo ${{ github.ref_name }} | sed 's|[^a-zA-Z0-9\\.\\-\\_]|-|g' )"
-      IMAGE_DEV_TEST:     "${{ inputs.TARGET_IMAGE_TEST }}:dev-$( echo ${{ github.ref_name }} | sed 's|[^a-zA-Z0-9\\.\\-\\_]|-|g' )"
-      IMAGE_RELEASE_PROD: "${{ inputs.TARGET_IMAGE_PROD }}:$( echo ${{ github.event.release.name }} | sed 's|[^a-zA-Z0-9\\.\\-\\_]|-|g' )"
-      IMAGE_RELEASE_TEST: "${{ inputs.TARGET_IMAGE_TEST }}:$( echo ${{ github.event.release.name }} | sed 's|[^a-zA-Z0-9\\.\\-\\_]|-|g' )"
-      IMAGE_LATEST_PROD:  "${{ inputs.TARGET_IMAGE_PROD }}:latest"
-      IMAGE_LATEST_TEST:  "${{ inputs.TARGET_IMAGE_TEST }}:latest"
-
-      # The build cache is used to cache Docker layers, used to speed up the build process.
-      # If the image gets too big, it can be removed from Docker Hub,
-      #   it will create a new cache automatically, the first build after removal will only be slower.
-      IMAGE_BUILD_CACHE:  "${{ inputs.TARGET_IMAGE_CACHE }}:latest"
     steps:
+
+    - name: Set variables
+      id: vars
+      # Remove special characters in tag name with sed
+      run: |
+        {
+          echo "IMAGE_PROD=${{ inputs.TARGET_IMAGE_PROD }}:$( echo ${{ inputs.TARGET_IMAGE_TAG }} | sed 's|[^a-zA-Z0-9\\.\\-\\_]|-|g' | awk '{print tolower($0)}' )";
+          echo "IMAGE_PROD_LATEST=${{ inputs.TARGET_IMAGE_PROD }}:latest";
+          echo "IMAGE_TEST=${{ inputs.TARGET_IMAGE_TEST }}:$( echo ${{ inputs.TARGET_IMAGE_TAG }} | sed 's|[^a-zA-Z0-9\\.\\-\\_]|-|g' | awk '{print tolower($0)}' )";
+          echo "IMAGE_BUILD_CACHE=${{ inputs.TARGET_IMAGE_CACHE }}:cache"
+        } >> "$GITHUB_OUTPUT"
+
+    - name: Debug variables
+      run: |
+        echo "IMAGE_PROD=${{ steps.vars.outputs.IMAGE_PROD }}"
+        echo "IMAGE_PROD_LATEST=${{ steps.vars.outputs.IMAGE_PROD_LATEST }}"
+        echo "IMAGE_TEST=${{ steps.vars.outputs.IMAGE_TEST }}"
+        echo "IMAGE_BUILD_CACHE=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}"
 
 
       # Use a hash (commit) and not a short release-version to make sure it has not been tampered with
@@ -56,64 +65,100 @@ jobs:
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # https://github.com/actions/checkout/releases/tag/v4.2.2
 
 
+
     - name: Login to Docker Hub
       uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # https://github.com/docker/login-action/releases/tag/v3.3.0
       with:
         username: ${{ inputs.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
 
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # https://github.com/docker/setup-qemu-action/releases/tag/v3.3.0
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # https://github.com/docker/setup-buildx-action/releases/tag/v3.8.0
 
 
-    - name: Build test image
+
+    - name: Build + cache test image (only linux/amd64)
       uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # https://github.com/docker/build-push-action/releases/tag/v6.12.0
       with:
         load: true
         target: final_test
-        tags: local/docker/image:test
-        cache-from: type=registry,ref=${{ env.IMAGE_BUILD_CACHE }}
-        cache-to: type=registry,ref=${{ env.IMAGE_BUILD_CACHE }},mode=max
+        tags: ${{ steps.vars.outputs.IMAGE_TEST }}
+        platforms: linux/amd64
+        cache-from: type=registry,ref=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}-test_linux_amd64
+        cache-to: type=registry,ref=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}-test_linux_amd64,mode=max
 
 
-    - name: Run tests
+
+    - name: Run tests (linux/amd64)
+      timeout-minutes: 5
       run: |
-        docker run --rm local/docker/image:test vendor/bin/phpcs
-        docker run --rm local/docker/image:test vendor/bin/phpstan --memory-limit=512M analyse src tests
-        docker run --rm local/docker/image:test vendor/bin/phpunit
+        docker images ${{ steps.vars.outputs.IMAGE_TEST }}
+        docker run --rm --platform linux/amd64 ${{ steps.vars.outputs.IMAGE_TEST }} php vendor/bin/phpcs
+        docker run --rm --platform linux/amd64 ${{ steps.vars.outputs.IMAGE_TEST }} php vendor/bin/phpstan --memory-limit=512M analyse src tests
+        docker run --rm --platform linux/amd64 ${{ steps.vars.outputs.IMAGE_TEST }} php vendor/bin/phpunit
+
+        # run a detached container
+        docker run --rm --platform linux/amd64 -d --name running_test_container -p 8250:8250 ${{ steps.vars.outputs.IMAGE_TEST }}
+        
+        # wait until container is healthy
+        timeout 15s sh -c 'until docker ps | grep -w running_test_container | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 1; done'
+
+        # try to see if the container is really serving the CMS (otherwise try to remove the container, and exit with errorcode 1)
+        curl --silent http://localhost:8250 | grep "<!-- MakeItStatic-CMS - https://makeitstatic.com -->" || (docker rm running_test_container --force; echo "ERROR: It seems the container is not serving any webapp???"; exit 1)
+
+        echo "Success - the container is serving the webapp"
+
+        # stop/remove the container
+        docker rm running_test_container --force
 
 
-    - if: ${{ inputs.DOCKER_PUSH_DEV == 1 || inputs.DOCKER_PUSH_RELEASE == 1 }}
-      name: Build production image
+    - if: ${{ inputs.DOCKER_PUSH == 1 && inputs.DOCKER_PUSH_LATEST != 1 }}
+      name: Build + push production image (dev-main) (linux/amd64,linux/arm64)
+      uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # https://github.com/docker/build-push-action/releases/tag/v6.12.0
+      with:
+        push: true
+        target: final_prod
+        tags: ${{ steps.vars.outputs.IMAGE_PROD }}
+        platforms: linux/amd64,linux/arm64
+        cache-from: |
+          type=registry,ref=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}-prod_linux_amd64
+          type=registry,ref=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}-prod_linux_arm64
+
+    - if: ${{ inputs.DOCKER_PUSH == 1 && inputs.DOCKER_PUSH_LATEST == 1 }}
+      name: Build + push production image (release + latest) (linux/amd64,linux/arm64)
+      uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # https://github.com/docker/build-push-action/releases/tag/v6.12.0
+      with:
+        push: true
+        target: final_prod
+        tags: |
+          ${{ steps.vars.outputs.IMAGE_PROD }}
+          ${{ steps.vars.outputs.IMAGE_PROD_LATEST }}
+        platforms: linux/amd64,linux/arm64
+        cache-from: |
+          type=registry,ref=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}-prod_linux_amd64
+          type=registry,ref=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}-prod_linux_arm64
+
+    - if: ${{ inputs.DOCKER_PUSH == 1 }}
+      name: Cache production image layers (prod_linux_amd64)
       uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # https://github.com/docker/build-push-action/releases/tag/v6.12.0
       with:
         load: true
         target: final_prod
-        tags: local/docker/image:prod
-        cache-from: type=registry,ref=${{ env.IMAGE_BUILD_CACHE }}
-        cache-to: type=registry,ref=${{ env.IMAGE_BUILD_CACHE }},mode=max
+        tags: ${{ steps.vars.outputs.IMAGE_PROD }}
+        platforms: linux/amd64
+        cache-from: type=registry,ref=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}-prod_linux_amd64
+        cache-to: type=registry,ref=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}-prod_linux_amd64,mode=max
 
-
-    - if: ${{ inputs.DOCKER_PUSH_DEV == 1 }}
-      name: Docker push developer image
-      run: |
-        docker tag local/docker/image:prod ${{ env.IMAGE_DEV_PROD }}
-        docker push ${{ env.IMAGE_DEV_PROD }}
-
-        docker tag local/docker/image:test ${{ env.IMAGE_DEV_TEST }}
-        docker push ${{ env.IMAGE_DEV_TEST }}
-
-
-    - if: ${{ inputs.DOCKER_PUSH_RELEASE == 1 }}
-      name: Docker push release + latest
-      run: |
-        docker tag local/docker/image:prod ${{ env.IMAGE_RELEASE_PROD }}
-        docker tag local/docker/image:prod ${{ env.IMAGE_LATEST_PROD }}
-        docker push ${{ env.IMAGE_RELEASE_PROD }}
-        docker push ${{ env.IMAGE_LATEST_PROD }}
-        
-        docker tag local/docker/image:test ${{ env.IMAGE_RELEASE_TEST }}
-        docker tag local/docker/image:test ${{ env.IMAGE_LATEST_TEST }}
-        docker push ${{ env.IMAGE_RELEASE_TEST }}
-        docker push ${{ env.IMAGE_LATEST_TEST }}
+    - if: ${{ inputs.DOCKER_PUSH == 1 }}
+      name: Cache production image layers (prod_linux_arm64)
+      uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # https://github.com/docker/build-push-action/releases/tag/v6.12.0
+      with:
+        load: true
+        target: final_prod
+        tags: ${{ steps.vars.outputs.IMAGE_PROD }}
+        platforms: linux/arm64
+        cache-from: type=registry,ref=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}-prod_linux_arm64
+        cache-to: type=registry,ref=${{ steps.vars.outputs.IMAGE_BUILD_CACHE }}-prod_linux_arm64,mode=max
